title: Blog
children:
  - title: Ambient Computing
    path: /ambient-computing
  - title: Predictions 2025
    path: /predictions-2025
  - title: Raycast Train Times
    path: /raycast-train-times
